auth_enabled: false

server:
  http_listen_port: 3100

common:
  storage:
    s3:
      bucketnames: "<your-s3-bucket-name>"
      endpoint: "s3.<region>.amazonaws.com"
      access_key_id: "<your-access-key>"
      secret_access_key: "<your-secret-key>"
      s3forcepathstyle: false
      insecure: false
  replication_factor: 1

schema_config:
  configs:
    - from: 2022-10-24
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: index_
        period: 24h

ruler:
  storage:
    type: local
    local:
      directory: /loki/rules

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  ingestion_rate_mb: 64
  ingestion_burst_size_mb: 128

chunk_store_config:
  max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: true
  retention_period: 7d
